### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [phadej/overloaded#6]
I understand what this package does but I don't understand why you would want to do it.

**Comment by googleson78** [comment]
I can give some reasons why **I** like this:

0. Everyone could want his own `Overloaded*` extension, because it's useful for his use case. But it doesn't mean it's useful for everyone using `ghc`, and it also doesn't mean that `ghc` should take on the development/sustainability effort of implementing/supporting such a thing.
1. This already has more `Overloaded*` stuff implemented than `ghc`, so it is strictly better in that area.
2. (I hope) There is the potential for these to be safer than the default - right now if I write `(-1) :: Natural` it will compile, but only blow up at runtime. (or `[] :: NonEmpty Int`)
3. It's just plain cool you can implement something that used to be builtin.

**Comment by phadej** [comment]
Thanks for answering, @googleson78.

My main motivation is the 3. point. To implement something that is builtin, or *could be* built-in.

For example there is an abandoned [compile-time literals proposal](https://github.com/ghc-proposals/ghc-proposals/pull/124), particularly https://github.com/ghc-proposals/ghc-proposals/pull/124#issuecomment-382267220 comment.

---

INote in 2. `(-1) :: Natural` will still compile, as it's `negate 1 :: Natural`. partial `negate` is culprit. (With `-XNegativeLiterals` and `-Wall` GHC warns about out-of-range literal).

`[] :: NonEmpty Int` is a better example. In fact, this ties to 0. and 1. point. `Oveloaded:Lists` desugars lists to members of different classes, not to [IsList via built-in OverloadedLists](https://downloads.haskell.org/~ghc/8.8.1/docs/html/users_guide/glasgow_exts.html#extension-OverloadedLists) (note: `overloaded` doesn't support patterns, (yet?)).
